version: '3'
services:
    main:
        container_name: djangobase
        image: python:3.7
        volumes:
            - .:/usr/src/djangobase
        working_dir: /usr/src/djangobase
        ports:
            - 8083:80
        command: /bin/bash -c "pip install -r requirements.txt && python manage.py runserver 8083"
